pipeline {
    agent {
        label "master"
    }
    environment {
        K6_SCRIPT = "${WORKSPACE}/jobs/ithome-day9-sample-k6-testing/ithome-sample.js"
    }    
    stages {
        stage('K6 cloud login'){
            steps {
                withCredentials([string(credentialsId: 'ithome-k6-cloud-token', variable: 'K6_CLOUD_TOKEN')]) {
                    sh "k6 login cloud -t ${K6_CLOUD_TOKEN}"
                }
            }
        }        
        stage('Sample request'){
            steps {
                sh "k6 run ${K6_SCRIPT} -o cloud"
            }
        }
    }
    post {
        always{
            archiveArtifacts artifacts: 'ithome-sample.html', followSymlinks: false
        }
    }    
}